#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'compareTriplets' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts following parameters:
#  1. INTEGER_ARRAY a
#  2. INTEGER_ARRAY b
#
#cannot specifiy the types here like i would in java
def compareTriplets(a, b):
    # Write your code here
    #how do i make the array input arbitrary
    #use a for loop
    alice = 0
    bob = 0
    for i in range(len(a)): #list cannot be interpreted as an integer. traceback error said so
        if a[i] > b[i]:
            alice += 1
        elif a[i] < b[i]:
            bob += 1
    return [alice, bob]
        
            
    '''score_a = 0
    score_b = 0
    if a[i] > b[i]:
        #increase alice's point by 1 when the value at the index in both arrays 
        #is being compared ahd alices is greater
        return a + 1
    elif a[i] < b[i]:
        #increase bob's point by 1
        return b + 1
    else:
        #neither person gets a point
        return [a, b]'''
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
